In [18]:
import pandas as pd

data = pd.read_html("https://www.mohfw.gov.in/index.html")

data = data[0]
data

,S. No.,Name of State / UT,Total Confirmed cases (Including 111 foreign Nationals),Cured/Discharged/Migrated,Deaths ( more than 70% cases due to comorbidities )
0,1,Andaman and Nicobar Islands,33,33,0
1,2,Andhra Pradesh,1847,780,38
2,3,Arunachal Pradesh,1,1,0
3,4,Assam,54,34,1
4,5,Bihar,550,246,5
5,6,Chandigarh,135,21,1
6,7,Chhattisgarh,59,38,0
7,8,Dadar Nagar Haveli,1,0,0
8,9,Delhi,5980,1931,66
9,10,Goa,7,7,0
10,11,Gujarat,7012,1709,425
11,12,Haryana,625,260,7
12,13,Himachal Pradesh,46,38,2
13,14,Jammu and Kashmir,793,335,9
14,15,Jharkhand,132,41,3
15,16,Karnataka,705,366,30
16,17,Kerala,503,474,4
17,18,Ladakh,42,17,0
18,19,Madhya Pradesh,3252,1231,193
19,20,Maharashtra,17974,3301,694
20,21,Manipur,2,2,0
21,22,Meghalaya,12,10,1
22,23,Mizoram,1,0,0
23,24,Odisha,219,62,2
24,25,Puducherry,9,6,0
25,26,Punjab,1644,149,28
26,27,Rajasthan,3427,1596,97
27,28,Tamil Nadu,5409,1547,37
28,29,Telengana,1123,650,29
29,30,Tripura,65,2,0
30,31,Uttarakhand,61,39,1
31,32,Uttar Pradesh,3071,1250,62
32,33,West Bengal,1548,364,151
33,Total number of confirmed cases in India,Total number of confirmed cases in India,56342*,16540,1886
34,*States wise distribution is subject to furthe...,*States wise distribution is subject to furthe...,*States wise distribution is subject to furthe...,*States wise distribution is subject to furthe...,*States wise distribution is subject to furthe...
35,*Our figures are being reconciled with ICMR,*Our figures are being reconciled with ICMR,*Our figures are being reconciled with ICMR,*Our figures are being reconciled with ICMR,*Our figures are being reconciled with ICMR